### ISSUE TITLE
Beastman portrait mapping

### ISSUE THREAD

**Issue by danreuben** [PrototypeESBU/foundryvtt-shadowdark-custom-module#1]
After installing the optional shadowdark-hombrew module, I was able to map the portraits/tokens for the minotaur and ettercap. Following the same instructions for the beastman did not work as expected. The token mapped properly but the portrait fails to render. I checked the artwork-mapping.json file to confirm the correct filename. All my webp files were exported from the same afdesign template used to generate the portraits/tokens.

filename: beastman.webp

**Comment by PrototypeESBU** [comment]
Are you able to share the beastman.webp file you're trying to use?

**Comment by danreuben** [comment]
Looks like the file was not the problem. The issue went away after updating the Shadowdark RPG module.
